apiVersion: harness.io/v1
kind: Component
type: service
identifier: java_backend_parson
name: Java Backend Parson
owner: user:account/todd.parson@harness.io
orgIdentifier: sandbox
projectIdentifier: parson
spec:
  lifecycle: development
  sourceCode:
    provider: Github
    repoName: harness-java-backend-parson
    connectorRef: parsonghharnessidpsandbox
    branch: main
    monoRepo: false
    url: https://github.com/harness-idp-sandbox/harness-java-backend-parson/tree/main
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: harness-java-backend-parson
    grafana/dashboard-selector: folderUrl == 'https://100.25.3.28.sslip.io/dashboards/f/bf34szb60u2gwe/harness'
    grafana/overview-dashboard: https://100.25.3.28.sslip.io/d/19a44328-b2d2-4fb2-bfa3-d379d069124a/jvm-micrometer?orgId=1&kiosk&var-application=java-backend-parson
    sonarqube.org/project-key: parson/harness-java-backend-parson
    backstage.io/kubernetes-label-selector: app=javabackendparson
    harness.io/sto-test-target:
    - name: boutique-web-ui
      scope: demo.Platform_Engineering
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/all/orgs/sandbox/projects/parson/pipelines/Java_App_Provisioner/pipeline-studio/?storeType=INLINE
  links:
  - title: Website
    url: http://harness.io
  tags:
  - java
